
  export const applicationData = [{
    "programName": "Doctrate",
    "appNo": "#500034",
    "submittedDate": "04/12/20 2:00 PM",
    "status": "Approved",
    "progressPercentage": 77,
    "applicationId": "PS20065",
    "applicantNameEng": "Gautam Kidiyoor",
    "applicantNameUrdu": "गौतम किडियूर",
    "emailId": "xyz@gmail.com",
    "phoneNo": "05368452688666",
    "documentId": "053-684-5268-8666",
    "gender": "Female",
    "age": 18,
    "commentsCount": 5,
    "assignedTo": "Attar Ansari",
    "reviewerName": "Kiran Kumbhar",
    "eligibility": "Eligible"
  },
  {
    "programName": "Master",
    "appNo": "#500035",
    "submittedDate": "05/20/25 3:00 PM",
    "status": "Interview Missed",
    "progressPercentage": 50,
    "applicationId": "PS20065",
    "applicantNameEng": "Nikhil T",
    "applicantNameUrdu": "निखिल टी",
    "emailId": "pqr@gmail.com",
    "phoneNo": "05368452688666",
    "documentId": "053-684-5268-8666",
    "gender": "Female",
    "age": 18,
    "commentsCount": 13,
    "assignedTo": "Vipin Gupta",
    "reviewerName": "Krishna Shinde",
    "eligibility": "Not Eligible"
  },
  {
    "programName": "Bachelor",
    "appNo": "#600035",
    "submittedDate": "14/12/20 4:00 PM",
    "status": "Withdrawn",
    "progressPercentage": 20,
    "applicationId": "PS20065",
    "applicantNameEng": "Samiksha Shukla",
    "applicantNameUrdu": "समिक्षा शुक्ला",
    "emailId": "lmn@gmail.com",
    "phoneNo": "05368452688666",
    "documentId": "053-684-5268-8666",
    "gender": "Male",
    "age": 22,
    "commentsCount": 2,
    "assignedTo": "Pankaj Sharma",
    "reviewerName": "Amit Vishwa",
    "eligibility": null
  },
  {
    "programName": "Master",
    "appNo": "#500035",
    "submittedDate": "05/20/25 3:00 PM",
    "status": "Interview Missed",
    "progressPercentage": 50,
    "applicationId": "PS20065",
    "applicantNameEng": "Nikhil T",
    "applicantNameUrdu": "निखिल टी",
    "emailId": "pqr@gmail.com",
    "phoneNo": "05368452688666",
    "documentId": "053-684-5268-8666",
    "gender": "Female",
    "age": 18,
    "commentsCount": 13,
    "assignedTo": "Vipin Gupta",
    "reviewerName": "Krishna Shinde",
    "eligibility": "Not Eligible"
  },
  {
    "programName": "Doctrate",
    "appNo": "#500034",
    "submittedDate": "04/12/20 2:00 PM",
    "status": "Approved",
    "progressPercentage": 77,
    "applicationId": "PS20065",
    "applicantNameEng": "Gautam Kidiyoor",
    "applicantNameUrdu": "गौतम किडियूर",
    "emailId": "xyz@gmail.com",
    "phoneNo": "05368452688666",
    "documentId": "053-684-5268-8666",
    "gender": "Female",
    "age": 18,
    "commentsCount": 5,
    "assignedTo": "Attar Ansari",
    "reviewerName": "Kiran Kumbhar",
    "eligibility": "Eligible"
  },
  {
    "programName": "Bachelor",
    "appNo": "#600035",
    "submittedDate": "14/12/20 4:00 PM",
    "status": "Withdrawn",
    "progressPercentage": 20,
    "applicationId": "PS20065",
    "applicantNameEng": "Samiksha Shukla",
    "applicantNameUrdu": "समिक्षा शुक्ला",
    "emailId": "lmn@gmail.com",
    "phoneNo": "05368452688666",
    "documentId": "053-684-5268-8666",
    "gender": "Male",
    "age": 22,
    "commentsCount": 2,
    "assignedTo": "Pankaj Sharma",
    "reviewerName": "Amit Vishwa",
    "eligibility": null
  }
]
